### ISSUE TITLE
Add Hotkey for Indicating Reaction

### ISSUE THREAD

**Issue by Ryzar** [14to9/combat-actors#18]
Allocate hotkey `7` to show that a character has used its reaction

**Comment by eephillip** [comment]
lol implemented, best graphic I could come up with.
<img width="512" alt="image" src="https://user-images.githubusercontent.com/470759/42735580-239d658c-881c-11e8-8e44-361df59d3211.png">

**Comment by eephillip** [comment]
![image](https://user-images.githubusercontent.com/470759/42740221-b4842e44-8869-11e8-8261-b83adfaa0a11.png)

**Comment by eephillip** [comment]
Find a way to indicate status on the actor entry instead of a miniature icon in the actor list

**Comment by pbev-lg** [comment]
aahhh nice!

**Comment by eephillip** [comment]
ahhh nice!
